-- 취소되지 않은 진료 예약 조회하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/132204

SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A
JOIN DOCTOR AS D
    ON A.MDDR_ID = D.DR_ID
JOIN PATIENT AS P
    ON A.PT_NO = P.PT_NO
WHERE A.APNT_CNCL_YMD IS NULL
    AND A.MCDP_CD = 'CS'
    AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD ASC